name: ollama

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    pull_policy: always
    restart: unless-stopped
    # Uncomment below for GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities:
    #             - gpu

    # Uncomment below to expose Ollama API outside the container stack
    # ports:
    #   - 11435:11434
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ollama-net
    # tty: true

  nginx:
    image: nginx
    container_name: ollama_nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./apikeys.conf:/etc/nginx/apikeys.conf:ro
      - ./application.log:/var/log/nginx/access.log
      - ./application.log:/var/log/nginx/auth_access.log
    ports:
      - 5050:5050
    networks:
      - ollama-net

volumes:
  ollama_data:

networks:
  ollama-net:
    driver: bridge

